version: '3.9'

services:
  remotely:
    container_name: remotely
    image: immybot/remotely:latest
    volumes:
      - /var/www/remotely:/remotely-data
    ports:
      - 5000:5000
    restart: unless-stopped